name: Build project & Check formatting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Check formatting
        run: make format && git diff --quiet
